
GET https://can-of-books-backend-0qwx.onrender.com/books

### 
PUT http://localhost:3001/books/64ee84465c9bbcb2431a6e48
Content-Type: application/json

{
    "title": "Ender's Game",
    "description": "Children trained to be military geniuses to fight against alien invasions.",
    "status": "read"
}

###
GET http://localhost:3001/books
### 
POST http://localhost:3001/books
Content-Type: application/json

{
    "userEmail": "sugaraspa@gmail.com",
    "title": "joejoe",
    "description": "Children trained to be military geniuses to fight against alien invasions.",
    "status": "unread"
}
### 
DELETE http://localhost:3001/books/64ee5fa248aa64f86bd2ac3b

